name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Navigate to frontend directory and list files
      - name: Navigate to frontend
        working-directory: frontend
        run: |
          ls -la

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Step 4: Build the frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run src

      # Step 5: Deploy to Azure Web App
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ 29dd5e15-f8b6-41d6-a972-b066718e145b }}
          tenant-id: ${{ 391ffc51-be99-4961-871d-95b34bd4f8c7 }}
          client-secret: ${{ 768f3ea3-97fc-40d0-94a0-163f89a4684f }}


