name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Navigate to the frontend directory
      - name: Navigate to frontend
        working-directory: frontend
        run: |
          ls -la # Optional: List files to confirm the directory

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Step 4: Build the frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Step 5: Deploy to Azure (optional)
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "https://chatbot-in-testing.azurewebsites.net/"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./frontend/build

